New latency update
gthparch/macsim pull request #31
Opened 2020-08-04 16:11 UTC by mgoldstein322

Added latency data for skylake, skylake-x, and coffee lake architectures; created a knob called uop_latency_map that allows the user to choose which of the x86 delay maps are in use; corrected some redundancy in the uoplatency files.

2020-08-04 18:00 UTC, hyojongk commented on src/trace_read_cpu.h
> +    //changed my Michael
by

2020-08-04 18:03 UTC, hyojongk requested changes
fix a typo

2020-08-04 18:12 UTC, hyojongk approved these changes

2020-08-07 18:59 UTC, hyesoon approved these changes

2020-08-08 23:25 UTC, merged